// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_gmmdist_l2
double cpp_gmmdist_l2(arma::vec weight1, arma::mat mean1, arma::cube variance1, arma::vec weight2, arma::mat mean2, arma::cube variance2);
RcppExport SEXP _gmmtools_cpp_gmmdist_l2(SEXP weight1SEXP, SEXP mean1SEXP, SEXP variance1SEXP, SEXP weight2SEXP, SEXP mean2SEXP, SEXP variance2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance1(variance1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance2(variance2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmdist_l2(weight1, mean1, variance1, weight2, mean2, variance2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmdist_cs
double cpp_gmmdist_cs(arma::vec weight1, arma::mat mean1, arma::cube variance1, arma::vec weight2, arma::mat mean2, arma::cube variance2);
RcppExport SEXP _gmmtools_cpp_gmmdist_cs(SEXP weight1SEXP, SEXP mean1SEXP, SEXP variance1SEXP, SEXP weight2SEXP, SEXP mean2SEXP, SEXP variance2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance1(variance1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance2(variance2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmdist_cs(weight1, mean1, variance1, weight2, mean2, variance2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmdist_klga
double cpp_gmmdist_klga(arma::vec weight1, arma::mat mean1, arma::cube variance1, arma::vec weight2, arma::mat mean2, arma::cube variance2);
RcppExport SEXP _gmmtools_cpp_gmmdist_klga(SEXP weight1SEXP, SEXP mean1SEXP, SEXP variance1SEXP, SEXP weight2SEXP, SEXP mean2SEXP, SEXP variance2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance1(variance1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance2(variance2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmdist_klga(weight1, mean1, variance1, weight2, mean2, variance2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmdist_klsel
double cpp_gmmdist_klsel(arma::vec weight1, arma::mat mean1, arma::cube variance1, arma::vec weight2, arma::mat mean2, arma::cube variance2);
RcppExport SEXP _gmmtools_cpp_gmmdist_klsel(SEXP weight1SEXP, SEXP mean1SEXP, SEXP variance1SEXP, SEXP weight2SEXP, SEXP mean2SEXP, SEXP variance2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance1(variance1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance2(variance2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmdist_klsel(weight1, mean1, variance1, weight2, mean2, variance2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmdist_klpog
double cpp_gmmdist_klpog(arma::vec weight1, arma::mat mean1, arma::cube variance1, arma::vec weight2, arma::mat mean2, arma::cube variance2);
RcppExport SEXP _gmmtools_cpp_gmmdist_klpog(SEXP weight1SEXP, SEXP mean1SEXP, SEXP variance1SEXP, SEXP weight2SEXP, SEXP mean2SEXP, SEXP variance2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance1(variance1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance2(variance2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmdist_klpog(weight1, mean1, variance1, weight2, mean2, variance2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmdist_klmb
double cpp_gmmdist_klmb(arma::vec weight1, arma::mat mean1, arma::cube variance1, arma::vec weight2, arma::mat mean2, arma::cube variance2);
RcppExport SEXP _gmmtools_cpp_gmmdist_klmb(SEXP weight1SEXP, SEXP mean1SEXP, SEXP variance1SEXP, SEXP weight2SEXP, SEXP mean2SEXP, SEXP variance2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance1(variance1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance2(variance2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmdist_klmb(weight1, mean1, variance1, weight2, mean2, variance2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmdist_klvlb
double cpp_gmmdist_klvlb(arma::vec weight1, arma::mat mean1, arma::cube variance1, arma::vec weight2, arma::mat mean2, arma::cube variance2);
RcppExport SEXP _gmmtools_cpp_gmmdist_klvlb(SEXP weight1SEXP, SEXP mean1SEXP, SEXP variance1SEXP, SEXP weight2SEXP, SEXP mean2SEXP, SEXP variance2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance1(variance1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance2(variance2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmdist_klvlb(weight1, mean1, variance1, weight2, mean2, variance2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmdist_klvub
double cpp_gmmdist_klvub(arma::vec weight1, arma::mat mean1, arma::cube variance1, arma::vec weight2, arma::mat mean2, arma::cube variance2);
RcppExport SEXP _gmmtools_cpp_gmmdist_klvub(SEXP weight1SEXP, SEXP mean1SEXP, SEXP variance1SEXP, SEXP weight2SEXP, SEXP mean2SEXP, SEXP variance2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance1(variance1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance2(variance2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmdist_klvub(weight1, mean1, variance1, weight2, mean2, variance2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmdist_jr
double cpp_gmmdist_jr(arma::vec weight1, arma::mat mean1, arma::cube variance1, arma::vec weight2, arma::mat mean2, arma::cube variance2);
RcppExport SEXP _gmmtools_cpp_gmmdist_jr(SEXP weight1SEXP, SEXP mean1SEXP, SEXP variance1SEXP, SEXP weight2SEXP, SEXP mean2SEXP, SEXP variance2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance1(variance1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance2(variance2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmdist_jr(weight1, mean1, variance1, weight2, mean2, variance2));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmdist_he
double cpp_gmmdist_he(arma::vec weight1, arma::mat mean1, arma::cube variance1, arma::vec weight2, arma::mat mean2, arma::cube variance2, double theta);
RcppExport SEXP _gmmtools_cpp_gmmdist_he(SEXP weight1SEXP, SEXP mean1SEXP, SEXP variance1SEXP, SEXP weight2SEXP, SEXP mean2SEXP, SEXP variance2SEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance1(variance1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance2(variance2SEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmdist_he(weight1, mean1, variance1, weight2, mean2, variance2, theta));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmdist_tsl
double cpp_gmmdist_tsl(arma::vec weight1, arma::mat mean1, arma::cube variance1, arma::vec weight2, arma::mat mean2, arma::cube variance2);
RcppExport SEXP _gmmtools_cpp_gmmdist_tsl(SEXP weight1SEXP, SEXP mean1SEXP, SEXP variance1SEXP, SEXP weight2SEXP, SEXP mean2SEXP, SEXP variance2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance1(variance1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance2(variance2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmdist_tsl(weight1, mean1, variance1, weight2, mean2, variance2));
    return rcpp_result_gen;
END_RCPP
}
// gmm_skeleton
Rcpp::List gmm_skeleton(arma::mat& X, int k);
RcppExport SEXP _gmmtools_gmm_skeleton(SEXP XSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(gmm_skeleton(X, k));
    return rcpp_result_gen;
END_RCPP
}
// gmm_armadillo
Rcpp::List gmm_armadillo(arma::mat& X, int k, int maxiter, bool usediag);
RcppExport SEXP _gmmtools_gmm_armadillo(SEXP XSEXP, SEXP kSEXP, SEXP maxiterSEXP, SEXP usediagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type usediag(usediagSEXP);
    rcpp_result_gen = Rcpp::wrap(gmm_armadillo(X, k, maxiter, usediag));
    return rcpp_result_gen;
END_RCPP
}
// gmm_11R
Rcpp::List gmm_11R(arma::mat& X, int K, double lambda, int maxiter, bool usediag);
RcppExport SEXP _gmmtools_gmm_11R(SEXP XSEXP, SEXP KSEXP, SEXP lambdaSEXP, SEXP maxiterSEXP, SEXP usediagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type usediag(usediagSEXP);
    rcpp_result_gen = Rcpp::wrap(gmm_11R(X, K, lambda, maxiter, usediag));
    return rcpp_result_gen;
END_RCPP
}
// gmm_16Gfix
Rcpp::List gmm_16Gfix(arma::mat& X, int k, arma::vec weight, int maxiter, bool usediag);
RcppExport SEXP _gmmtools_gmm_16Gfix(SEXP XSEXP, SEXP kSEXP, SEXP weightSEXP, SEXP maxiterSEXP, SEXP usediagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type usediag(usediagSEXP);
    rcpp_result_gen = Rcpp::wrap(gmm_16Gfix(X, k, weight, maxiter, usediag));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmcombine_tsl
double cpp_gmmcombine_tsl(arma::vec weight, arma::mat mean, arma::cube variance);
RcppExport SEXP _gmmtools_cpp_gmmcombine_tsl(SEXP weightSEXP, SEXP meanSEXP, SEXP varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type variance(varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmcombine_tsl(weight, mean, variance));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmcombine_medianL2
Rcpp::List cpp_gmmcombine_medianL2(Rcpp::List& gmmlist, arma::vec& vecpi, int maxiter, double abstol);
RcppExport SEXP _gmmtools_cpp_gmmcombine_medianL2(SEXP gmmlistSEXP, SEXP vecpiSEXP, SEXP maxiterSEXP, SEXP abstolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type gmmlist(gmmlistSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type vecpi(vecpiSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmcombine_medianL2(gmmlist, vecpi, maxiter, abstol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gmmcombine_medianHE
Rcpp::List cpp_gmmcombine_medianHE(Rcpp::List& gmmlist, arma::vec& vecpi, int maxiter, double abstol, double theta);
RcppExport SEXP _gmmtools_cpp_gmmcombine_medianHE(SEXP gmmlistSEXP, SEXP vecpiSEXP, SEXP maxiterSEXP, SEXP abstolSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type gmmlist(gmmlistSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type vecpi(vecpiSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gmmcombine_medianHE(gmmlist, vecpi, maxiter, abstol, theta));
    return rcpp_result_gen;
END_RCPP
}
// cpp_collapse_MPM
Rcpp::List cpp_collapse_MPM(arma::vec& weight, arma::mat& mean, arma::cube& vars);
RcppExport SEXP _gmmtools_cpp_collapse_MPM(SEXP weightSEXP, SEXP meanSEXP, SEXP varsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type vars(varsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_collapse_MPM(weight, mean, vars));
    return rcpp_result_gen;
END_RCPP
}
// cpp_collapse_W2
Rcpp::List cpp_collapse_W2(arma::vec& weight, arma::mat& mean, arma::cube& vars);
RcppExport SEXP _gmmtools_cpp_collapse_W2(SEXP weightSEXP, SEXP meanSEXP, SEXP varsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type vars(varsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_collapse_W2(weight, mean, vars));
    return rcpp_result_gen;
END_RCPP
}
// cpp_reduction_1990S
Rcpp::List cpp_reduction_1990S(arma::vec& weight, arma::mat& mean, arma::cube& vars, int M);
RcppExport SEXP _gmmtools_cpp_reduction_1990S(SEXP weightSEXP, SEXP meanSEXP, SEXP varsSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_reduction_1990S(weight, mean, vars, M));
    return rcpp_result_gen;
END_RCPP
}
// cpp_reduction_2003W
Rcpp::List cpp_reduction_2003W(arma::vec& weight, arma::mat& mean, arma::cube& vars, int M);
RcppExport SEXP _gmmtools_cpp_reduction_2003W(SEXP weightSEXP, SEXP meanSEXP, SEXP varsSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_reduction_2003W(weight, mean, vars, M));
    return rcpp_result_gen;
END_RCPP
}
// cpp_reduction_2007R
Rcpp::List cpp_reduction_2007R(arma::vec& weight, arma::mat& mean, arma::cube& vars, int M);
RcppExport SEXP _gmmtools_cpp_reduction_2007R(SEXP weightSEXP, SEXP meanSEXP, SEXP varsSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_reduction_2007R(weight, mean, vars, M));
    return rcpp_result_gen;
END_RCPP
}
// cpp_reduction_2021YS
Rcpp::List cpp_reduction_2021YS(arma::vec& weight, arma::mat& mean, arma::cube& vars, int M, double theta, std::string merger);
RcppExport SEXP _gmmtools_cpp_reduction_2021YS(SEXP weightSEXP, SEXP meanSEXP, SEXP varsSEXP, SEXP MSEXP, SEXP thetaSEXP, SEXP mergerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< std::string >::type merger(mergerSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_reduction_2021YS(weight, mean, vars, M, theta, merger));
    return rcpp_result_gen;
END_RCPP
}
// cpp_reduction_2021YP
arma::mat cpp_reduction_2021YP(arma::vec& weight, arma::mat& mean, arma::cube& vars, double theta);
RcppExport SEXP _gmmtools_cpp_reduction_2021YP(SEXP weightSEXP, SEXP meanSEXP, SEXP varsSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_reduction_2021YP(weight, mean, vars, theta));
    return rcpp_result_gen;
END_RCPP
}
// gmm_basedist2
arma::mat gmm_basedist2(arma::mat& mean1, arma::cube& var1, arma::mat& mean2, arma::cube& var2, std::string distopt);
RcppExport SEXP _gmmtools_gmm_basedist2(SEXP mean1SEXP, SEXP var1SEXP, SEXP mean2SEXP, SEXP var2SEXP, SEXP distoptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type mean1(mean1SEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type var1(var1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mean2(mean2SEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type var2(var2SEXP);
    Rcpp::traits::input_parameter< std::string >::type distopt(distoptSEXP);
    rcpp_result_gen = Rcpp::wrap(gmm_basedist2(mean1, var1, mean2, var2, distopt));
    return rcpp_result_gen;
END_RCPP
}
// gmm_density
arma::vec gmm_density(arma::mat& coords, arma::vec& weight, arma::mat& mean, arma::cube& variance);
RcppExport SEXP _gmmtools_gmm_density(SEXP coordsSEXP, SEXP weightSEXP, SEXP meanSEXP, SEXP varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type variance(varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(gmm_density(coords, weight, mean, variance));
    return rcpp_result_gen;
END_RCPP
}
// gmm_sample
arma::mat gmm_sample(int n, arma::colvec oldweight, arma::mat oldmeans, arma::cube oldcovs);
RcppExport SEXP _gmmtools_gmm_sample(SEXP nSEXP, SEXP oldweightSEXP, SEXP oldmeansSEXP, SEXP oldcovsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type oldweight(oldweightSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type oldmeans(oldmeansSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type oldcovs(oldcovsSEXP);
    rcpp_result_gen = Rcpp::wrap(gmm_sample(n, oldweight, oldmeans, oldcovs));
    return rcpp_result_gen;
END_RCPP
}
// eval_label
arma::uvec eval_label(arma::mat& X, arma::mat parMU, arma::cube parSIG, arma::vec parPI);
RcppExport SEXP _gmmtools_eval_label(SEXP XSEXP, SEXP parMUSEXP, SEXP parSIGSEXP, SEXP parPISEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type parMU(parMUSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type parSIG(parSIGSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type parPI(parPISEXP);
    rcpp_result_gen = Rcpp::wrap(eval_label(X, parMU, parSIG, parPI));
    return rcpp_result_gen;
END_RCPP
}
// gauss_rmvnorm
arma::mat gauss_rmvnorm(int N, arma::vec mu, arma::mat var);
RcppExport SEXP _gmmtools_gauss_rmvnorm(SEXP NSEXP, SEXP muSEXP, SEXP varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type var(varSEXP);
    rcpp_result_gen = Rcpp::wrap(gauss_rmvnorm(N, mu, var));
    return rcpp_result_gen;
END_RCPP
}
// gmm_together
Rcpp::List gmm_together(Rcpp::List& gmmlist, arma::vec& weight);
RcppExport SEXP _gmmtools_gmm_together(SEXP gmmlistSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type gmmlist(gmmlistSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    rcpp_result_gen = Rcpp::wrap(gmm_together(gmmlist, weight));
    return rcpp_result_gen;
END_RCPP
}
// cpp_setdiff
arma::uvec cpp_setdiff(arma::uvec& x, arma::uvec& y);
RcppExport SEXP _gmmtools_cpp_setdiff(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_setdiff(x, y));
    return rcpp_result_gen;
END_RCPP
}
// label_kmeans
arma::urowvec label_kmeans(arma::mat data, int K, int maxiter);
RcppExport SEXP _gmmtools_label_kmeans(SEXP dataSEXP, SEXP KSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(label_kmeans(data, K, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// label_gmm
arma::urowvec label_gmm(arma::mat data, int K, int maxiter);
RcppExport SEXP _gmmtools_label_gmm(SEXP dataSEXP, SEXP KSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(label_gmm(data, K, maxiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gmmtools_cpp_gmmdist_l2", (DL_FUNC) &_gmmtools_cpp_gmmdist_l2, 6},
    {"_gmmtools_cpp_gmmdist_cs", (DL_FUNC) &_gmmtools_cpp_gmmdist_cs, 6},
    {"_gmmtools_cpp_gmmdist_klga", (DL_FUNC) &_gmmtools_cpp_gmmdist_klga, 6},
    {"_gmmtools_cpp_gmmdist_klsel", (DL_FUNC) &_gmmtools_cpp_gmmdist_klsel, 6},
    {"_gmmtools_cpp_gmmdist_klpog", (DL_FUNC) &_gmmtools_cpp_gmmdist_klpog, 6},
    {"_gmmtools_cpp_gmmdist_klmb", (DL_FUNC) &_gmmtools_cpp_gmmdist_klmb, 6},
    {"_gmmtools_cpp_gmmdist_klvlb", (DL_FUNC) &_gmmtools_cpp_gmmdist_klvlb, 6},
    {"_gmmtools_cpp_gmmdist_klvub", (DL_FUNC) &_gmmtools_cpp_gmmdist_klvub, 6},
    {"_gmmtools_cpp_gmmdist_jr", (DL_FUNC) &_gmmtools_cpp_gmmdist_jr, 6},
    {"_gmmtools_cpp_gmmdist_he", (DL_FUNC) &_gmmtools_cpp_gmmdist_he, 7},
    {"_gmmtools_cpp_gmmdist_tsl", (DL_FUNC) &_gmmtools_cpp_gmmdist_tsl, 6},
    {"_gmmtools_gmm_skeleton", (DL_FUNC) &_gmmtools_gmm_skeleton, 2},
    {"_gmmtools_gmm_armadillo", (DL_FUNC) &_gmmtools_gmm_armadillo, 4},
    {"_gmmtools_gmm_11R", (DL_FUNC) &_gmmtools_gmm_11R, 5},
    {"_gmmtools_gmm_16Gfix", (DL_FUNC) &_gmmtools_gmm_16Gfix, 5},
    {"_gmmtools_cpp_gmmcombine_tsl", (DL_FUNC) &_gmmtools_cpp_gmmcombine_tsl, 3},
    {"_gmmtools_cpp_gmmcombine_medianL2", (DL_FUNC) &_gmmtools_cpp_gmmcombine_medianL2, 4},
    {"_gmmtools_cpp_gmmcombine_medianHE", (DL_FUNC) &_gmmtools_cpp_gmmcombine_medianHE, 5},
    {"_gmmtools_cpp_collapse_MPM", (DL_FUNC) &_gmmtools_cpp_collapse_MPM, 3},
    {"_gmmtools_cpp_collapse_W2", (DL_FUNC) &_gmmtools_cpp_collapse_W2, 3},
    {"_gmmtools_cpp_reduction_1990S", (DL_FUNC) &_gmmtools_cpp_reduction_1990S, 4},
    {"_gmmtools_cpp_reduction_2003W", (DL_FUNC) &_gmmtools_cpp_reduction_2003W, 4},
    {"_gmmtools_cpp_reduction_2007R", (DL_FUNC) &_gmmtools_cpp_reduction_2007R, 4},
    {"_gmmtools_cpp_reduction_2021YS", (DL_FUNC) &_gmmtools_cpp_reduction_2021YS, 6},
    {"_gmmtools_cpp_reduction_2021YP", (DL_FUNC) &_gmmtools_cpp_reduction_2021YP, 4},
    {"_gmmtools_gmm_basedist2", (DL_FUNC) &_gmmtools_gmm_basedist2, 5},
    {"_gmmtools_gmm_density", (DL_FUNC) &_gmmtools_gmm_density, 4},
    {"_gmmtools_gmm_sample", (DL_FUNC) &_gmmtools_gmm_sample, 4},
    {"_gmmtools_eval_label", (DL_FUNC) &_gmmtools_eval_label, 4},
    {"_gmmtools_gauss_rmvnorm", (DL_FUNC) &_gmmtools_gauss_rmvnorm, 3},
    {"_gmmtools_gmm_together", (DL_FUNC) &_gmmtools_gmm_together, 2},
    {"_gmmtools_cpp_setdiff", (DL_FUNC) &_gmmtools_cpp_setdiff, 2},
    {"_gmmtools_label_kmeans", (DL_FUNC) &_gmmtools_label_kmeans, 3},
    {"_gmmtools_label_gmm", (DL_FUNC) &_gmmtools_label_gmm, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_gmmtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
