# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_gmmdist_l2 <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_gmmtools_cpp_gmmdist_l2', PACKAGE = 'gmmtools', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_cs <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_gmmtools_cpp_gmmdist_cs', PACKAGE = 'gmmtools', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_klga <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_gmmtools_cpp_gmmdist_klga', PACKAGE = 'gmmtools', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_klsel <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_gmmtools_cpp_gmmdist_klsel', PACKAGE = 'gmmtools', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_klpog <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_gmmtools_cpp_gmmdist_klpog', PACKAGE = 'gmmtools', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_klmb <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_gmmtools_cpp_gmmdist_klmb', PACKAGE = 'gmmtools', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_klvlb <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_gmmtools_cpp_gmmdist_klvlb', PACKAGE = 'gmmtools', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_klvub <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_gmmtools_cpp_gmmdist_klvub', PACKAGE = 'gmmtools', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_jr <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_gmmtools_cpp_gmmdist_jr', PACKAGE = 'gmmtools', weight1, mean1, variance1, weight2, mean2, variance2)
}

cpp_gmmdist_he <- function(weight1, mean1, variance1, weight2, mean2, variance2, theta) {
    .Call('_gmmtools_cpp_gmmdist_he', PACKAGE = 'gmmtools', weight1, mean1, variance1, weight2, mean2, variance2, theta)
}

cpp_gmmdist_tsl <- function(weight1, mean1, variance1, weight2, mean2, variance2) {
    .Call('_gmmtools_cpp_gmmdist_tsl', PACKAGE = 'gmmtools', weight1, mean1, variance1, weight2, mean2, variance2)
}

gmm_skeleton <- function(X, k) {
    .Call('_gmmtools_gmm_skeleton', PACKAGE = 'gmmtools', X, k)
}

gmm_armadillo <- function(X, k, maxiter, usediag) {
    .Call('_gmmtools_gmm_armadillo', PACKAGE = 'gmmtools', X, k, maxiter, usediag)
}

gmm_11R <- function(X, K, lambda, maxiter, usediag) {
    .Call('_gmmtools_gmm_11R', PACKAGE = 'gmmtools', X, K, lambda, maxiter, usediag)
}

gmm_16Gfix <- function(X, k, weight, maxiter, usediag) {
    .Call('_gmmtools_gmm_16Gfix', PACKAGE = 'gmmtools', X, k, weight, maxiter, usediag)
}

cpp_gmmcombine_tsl <- function(weight, mean, variance) {
    .Call('_gmmtools_cpp_gmmcombine_tsl', PACKAGE = 'gmmtools', weight, mean, variance)
}

cpp_gmmcombine_medianL2 <- function(gmmlist, vecpi, maxiter, abstol) {
    .Call('_gmmtools_cpp_gmmcombine_medianL2', PACKAGE = 'gmmtools', gmmlist, vecpi, maxiter, abstol)
}

cpp_gmmcombine_medianHE <- function(gmmlist, vecpi, maxiter, abstol, theta) {
    .Call('_gmmtools_cpp_gmmcombine_medianHE', PACKAGE = 'gmmtools', gmmlist, vecpi, maxiter, abstol, theta)
}

cpp_collapse_MPM <- function(weight, mean, vars) {
    .Call('_gmmtools_cpp_collapse_MPM', PACKAGE = 'gmmtools', weight, mean, vars)
}

cpp_collapse_W2 <- function(weight, mean, vars) {
    .Call('_gmmtools_cpp_collapse_W2', PACKAGE = 'gmmtools', weight, mean, vars)
}

cpp_reduction_1990S <- function(weight, mean, vars, M) {
    .Call('_gmmtools_cpp_reduction_1990S', PACKAGE = 'gmmtools', weight, mean, vars, M)
}

cpp_reduction_2003W <- function(weight, mean, vars, M) {
    .Call('_gmmtools_cpp_reduction_2003W', PACKAGE = 'gmmtools', weight, mean, vars, M)
}

cpp_reduction_2007R <- function(weight, mean, vars, M) {
    .Call('_gmmtools_cpp_reduction_2007R', PACKAGE = 'gmmtools', weight, mean, vars, M)
}

cpp_reduction_2021YS <- function(weight, mean, vars, M, theta, merger) {
    .Call('_gmmtools_cpp_reduction_2021YS', PACKAGE = 'gmmtools', weight, mean, vars, M, theta, merger)
}

cpp_reduction_2021YP <- function(weight, mean, vars, theta) {
    .Call('_gmmtools_cpp_reduction_2021YP', PACKAGE = 'gmmtools', weight, mean, vars, theta)
}

gmm_basedist2 <- function(mean1, var1, mean2, var2, distopt) {
    .Call('_gmmtools_gmm_basedist2', PACKAGE = 'gmmtools', mean1, var1, mean2, var2, distopt)
}

gmm_density <- function(coords, weight, mean, variance) {
    .Call('_gmmtools_gmm_density', PACKAGE = 'gmmtools', coords, weight, mean, variance)
}

gmm_sample <- function(n, oldweight, oldmeans, oldcovs) {
    .Call('_gmmtools_gmm_sample', PACKAGE = 'gmmtools', n, oldweight, oldmeans, oldcovs)
}

eval_label <- function(X, parMU, parSIG, parPI) {
    .Call('_gmmtools_eval_label', PACKAGE = 'gmmtools', X, parMU, parSIG, parPI)
}

gauss_rmvnorm <- function(N, mu, var) {
    .Call('_gmmtools_gauss_rmvnorm', PACKAGE = 'gmmtools', N, mu, var)
}

gmm_together <- function(gmmlist, weight) {
    .Call('_gmmtools_gmm_together', PACKAGE = 'gmmtools', gmmlist, weight)
}

cpp_setdiff <- function(x, y) {
    .Call('_gmmtools_cpp_setdiff', PACKAGE = 'gmmtools', x, y)
}

label_kmeans <- function(data, K, maxiter) {
    .Call('_gmmtools_label_kmeans', PACKAGE = 'gmmtools', data, K, maxiter)
}

label_gmm <- function(data, K, maxiter) {
    .Call('_gmmtools_label_gmm', PACKAGE = 'gmmtools', data, K, maxiter)
}

